
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    data-username: sa
    data-password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
#  security:
#    user:
#      name: admin
#      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerwithEureka: true
    fetchRegistry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}

#spring.security.user.name=user # Default user name.
#spring.security.user.password= # Password for the default user name.
#spring.security.user.roles= # Granted roles for the default user name.
server:
  port: 8091
